name: deploy

on:
  push:
    tags:
    - '*'

jobs:
  pypi:
    strategy:
      matrix:
        distribution: [bdist_wheel]
        python-3-version: [6, 7, 8, 9]
        include:
          - distribution: sdist
            python-3-version: 9

    name: Build Python 3.${{ matrix.python-3-version }} ${{ matrix.distribution }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.${{ matrix.python-3-version }}
      - name: Package sdist
        if: matrix.distribution == 'sdist'
        run: |
          pip install --upgrade setuptools wheel
          python setup.py ${{ matrix.distribution }}
      - name: Package bdist_wheel
        if: matrix.distribution == 'bdist_wheel'
        run: |
          pip install --upgrade setuptools wheel
          python setup.py ${{ matrix.distribution }} --python-tag 3${{ matrix.python-3-version}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/*

  upload_all:
    name: Upload files to PyPI
    needs: [pypi]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist
    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_PWD }}
